# Generated by Django 3.1 on 2020-11-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201113_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='embed',
            new_name='embedded',
        ),
    ]
